Hongik-Human-Developer/algorithm_study

hyejun/JavaStudy/day3.md
<https://programmers.co.kr/learn/courses/30/lessons/42584>
1. prices 배열의 0번째 요소부터 마지막 요소까지 비교한다.
2. 0번째 요소 => 1,2,3,4요소와 비교 / 1번째 요소 => 2,3,4요소와 비교해야 하므로, 
- 비교하는 기준 요소를 두고, 요소를 한칸씩 뒤로 움직이며, 기준요소와 비교한다.
3. 기준요소(i)와 비교요소(j)를 비교했을 때, 
-  i가 작다면 주식 가격이 떨어지지 않은것 이므로 answer[i]++;
-  i가 크다면 주식 가격이 떨어진 것이므로 answer[i]++,주식 가격이 떨어졌다면 더이상 비교할 필요가 없으므로 break;
4. 최종 답안인 answer에 변수 count를 대입한다.
```java
public int[] solution(int[] prices) {
int[] answer = new int[prices.length];
for(int i=0; i<prices.length; i++)
{
int count=0;
for(int j=i+1; j<prices.length; j++)
{
if(prices[i]<=prices[j]) count++;
else if(prices[i]>prices[j]) { 
answer[i]= count++;
break;
}
}
answer[i]= count;
}
return answer;
}
}
​
```
=> [ADD] Day3 solved

hyejun/JavaStudy/day4.md
<https://programmers.co.kr/learn/courses/30/lessons/12912>
- 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
- 예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
- a,b는 아래와 같은 세가지 상태로 구분된다.
- (1) a>b　(2)a<b　(3) a=b
1. (1) 혹은 (2) 일 때, 작은 수 부터 큰 수 까지의 합을 구하면 되는 문제이다. 때문에 Math.min함수와 Math.max 함수를 사용하여 구간의 합을 return한다.
2. (3) a=b 일 때, a와b가 동일하기 때문에, a혹은 b를 return한다. 
```java
public long solution(int a, int b) {
long answer = 0;
for(int i=Math.min(a, b); i<=Math.max(a, b); i++) answer+=i;
return answer;
}
}
```
- O(n)
- 삼항 연산자를 이용해 푸는 방법도 있다.
```java
public long solution(int a, int b) {
long answer = 0;
for (int i = ((a < b) ? a : b); i <= ((a < b) ? b : a); i++) answer += i;
return answer;
}
}
```
1. (Math.max, Math.min) …
=> [ADD] Day4 Solved

minhwan/javaStudy/day1.md
https://programmers.co.kr/learn/courses/30/lessons/12916
```java
public int solution(int a, int b) {
int result = 0;
if (a < b) {
for (int i = a; i <= b; i++) {
result += i;
}
} else {
for (int i = b; i <= a; i++) {
result += i;
}
}
return result;
}
}
```
*   두 정수 사이의 합을 구할때 복합대입연산자를 사용하여 result = result +i 에서 변수를 한번 생략해주어 처리속도를 향상시켰습니다.
#
https://programmers.co.kr/learn/courses/30/lessons/12912
```java
boolean solution(String s) {
boolean result = true;
s = s.toUpperCase();
int count =0;
for( int i=0; i<s.length();i++){
if(s.charAt(i)=='P')
count++;
else if(s.charAt(i)=='Y')
count --;
}
if(count==0)
return true;
else
return false;
}
}
```
* 알파벳 py에 대해 대소문자 구별을 필요로 하지 않은 조건에서 toUpperCase함수를 사용해 대문자로 통일시켜주고 문자열s에 대한 p의 개수만큼 카운트를 +해주고 y의 개수만큼 카운트를 해줬습니다.
* …
=> [ADD] day1 solved

jangwon/js_study/day1.md
https://programmers.co.kr/learn/courses/30/lessons/12912
- 반복문을 통한 풀이 
1. a와 b사이에 값을 구하는것이기 때문에 반복문을 통해 값을 누적시켜 풀었다. 
**풀이 1)**
```js
function solution(a, b) {
let result = 0;
if(a < b) {
for (let i = a; i <= b; i++) {
result = result + i
}
}else {
for(let i = b; i <= a; i++){
result = result + i
}
}
return result ; 
```
}
* **시간복잡도 O(N)**
for문 한바퀴 돌기 때문에 시간복잡도가 O(N)으로 나온다. 
https://programmers.co.kr/learn/courses/30/lessons/12916
- 카운트 변수를 직접 만들어서 풀이 
1. 문자열인 변수를 배열로 만들어 내장메소드를 사용 할 수 있게 처리 ```split()```
2. 대소문자 구분이 없기 때문에 모두 소문자로 바꾸어줌 ```toLowerCase()```
3. p와 y가 둘 다 없는 경우의 조건을 ```includes()``` 배열 내장메소드를 사용해 처리
4. ```for of```를 사용하여 배열의 요소를 순회하고 타겟 요소가 있는 경우 count변수의 값을 한개씩 늘려줌
5. 두 개의 카운트 변수인 countP, countY를 비교하여 결과값을 도출 
```js
function solution(s){
let arr = s.split("")
let countP = …
```
=> [ADD] Problem 1 solved

minhwan/javaStudy/day2.md
1. https://programmers.co.kr/learn/courses/30/lessons/12910
```java
class Solution{
public int[] solution(int[] arr, int divisor) {
int result[] = Arrays.stream(arr).filter(index -> index % divisor ==0).toArray();
//result 배열의 인덱스를  0으로 나누었을 때 나머지가 0 인 인덱스 추출            
Arrays.sort(result);
//오름차순 정렬
if(result.length ==0) {
result = new int[1];
result[0] = -1;
}
// 나누어 떨어지는 값이 없을경우 배열에 -1담아 리턴
System.out.println(Arrays.toString(result));
return result;
}
}
```
2. https://programmers.co.kr/learn/courses/30/lessons/12915
```java
public String[] solution(String[] strings, int n) {
Arrays.sort(strings, new Comparator<>() {
// 오름차순 정렬  Comparator 생성 후 compare 메서드 적용
@Override
public int compare(String a,String b) {
if(a.charAt(n) > …
```
=> [ADD] day2 solved

hyejun/JavaStudy/day5.md, hyejun/JavaStudy/day6.md, hyejun/tes.md
!![image](https://user-images.githubusercontent.com/45223821/106151525-c794d600-61bf-11eb-8f10-bf2326a31b4e.png)
<https://programmers.co.kr/learn/courses/30/lessons/12915?language=java>
1. n번째 문자를 문자열 앞에 붙여, n번째 문자로 비교하며 sort한다.
- n번째 문자를 추출하기 위해 charAt 메소드를 사용했다.
2. sort후 앞에 붙인 n번째 문자열을 제거한다.
- indexOf를 사용하여, 특수 문자를 ("/") 체크한다.
- subString을 사용하여 문자열을 자른다.
```java
public String[] solution(String[] strings, int n) {
String[] answer = new String[strings.length];
for(int i=0; i<strings.length; i++) {
char temp=strings[i].charAt(n);
answer[i]=strings[i].valueOf(temp)+"/"+strings[i];
}
Arrays.sort(answer);
for(int i=0; i<answer.length; i++) {
answer[i]=answer[i].substring(answer[i].indexOf("/")+1);
}
return answer;
}
}
```
--- …
=> [ADD] Day5 Solved

minhwan/javaStudy/day3.md
**완주 하지 못한 선수**
https://programmers.co.kr/learn/courses/30/lessons/42576
```java
public String solution(String[] participant, String[] completion) {
Arrays.sort(participant); // 참가자 오름차순 정렬시켜줌
Arrays.sort(completion);  // 완주자 오름차순 정렬시켜줌
for (int i =0; i<completion.length; i++) {
if(!participant[i].equals(completion[i])){
return participant[i];                     // for문 돌려 탐색 , i번째 참여자 ,완주자 불일치시, i번째 참여자 리턴
}       
}
return participant[completion.length]; //참가자
}
}
```
* 참가자, 완주자 배열 오름차순으로 정렬해줌 -> 정렬된 배열로 미완주자 판별을 위해서
* for문 돌려 i번째 참가자, 완주자 불일치시 i번째 참가자 리턴시켜줌 
```
import java.util.HashMap;
public String solution(String[] participant, String[] completion) {
String answer = "";
HashMap<String, Integer> hm = new HashMap<>();
for (String …
```
=> [NOT DONE] Day5 Solved (Except 2)

jangwon/js_study/Day6/problem1.md, jangwon/js_study/Day6/problem2.md, jangwon/js_study/Day6/problem3.md, jangwon/js_study/Day6/problem4.md, jangwon/js_study/Day6/problem5.md, problem/Day7/problem.md
**문제1**
https://programmers.co.kr/learn/courses/30/lessons/12933
```js
function solution(n) {
return +(n + "").split("").sort((a,b)=> b - a).join("")
}
```
**문제2**
https://programmers.co.kr/learn/courses/30/lessons/12937
```js
function solution(num) {
return num % 2 === 0 ? "Even" : "Odd"
}
```
**문제3**
https://programmers.co.kr/learn/courses/30/lessons/12948
```js
function solution(phone_number) {
let arr = phone_number.split("");
for(let i =0; i< arr.length -4; i++) {
arr[i] = "*"
}
return arr.join("");
}
```
**문제4**
https://programmers.co.kr/learn/courses/30/lessons/12943
**풀이1**
```js
function solution(num) {
const collatzRecursive = (input , count) => {
if(count > 500) return -1;
if(input === 1) return count;
if(input % 2 === 0 ) return  collatzRecursive(input / 2, count +1);
else …
```
=> [ADD] Day6 all solved

minhwan/javaStudy/day5.md, minhwan/javaStudy/day6.md
**문제1**
https://programmers.co.kr/learn/courses/30/lessons/12933
```java
public long solution(long n) {
long answer = 0;
String str =String.valueOf(n);
char[] ch =str.toCharArray();
Arrays.sort(ch);
str= "";
for(int i =ch.length-1;i>=0;i--) {
str+=ch[i];
}
answer = Long.parseLong(str);
return answer;
}
}
```
* 스트링변수에 String.valueOf로 n값을 문자열로 저장,  toCharArray를 이용 문자열을 char형 배열에 담아줌 
* Arrays.sort로 배열 오름차순 정렬, 배열의 역순으로 for문 돌려 저장 
정수형long 으로 변환  answer에 저장
**문제2**
https://programmers.co.kr/learn/courses/30/lessons/12937
```java
public String solution(int num) {
return num%2 ==0 ? "Even": "Odd";
}
}
```
* 삼항연산자 이용 
**문제3**
https://programmers.co.kr/learn/courses/30/lessons/12948
```java
public String solution(String …
```
=> [ADD]Day6 solved

jangwon/js_study/Day7/problem.5.md, jangwon/js_study/Day7/problem1.md, jangwon/js_study/Day7/problem2.md, jangwon/js_study/Day7/problem3.md, jangwon/js_study/Day7/problem4.md, problem/Day7/problem.md, problem/Day8/problem1.md
**문제1** 
https://programmers.co.kr/learn/courses/30/lessons/12947
**문제 풀이**
1. 주어진 x값을 문자열로 변환 ```toString()``` 대신 ``` + "" ``` 로 문자열을 처리함
2. 배열 메소드를 사용하기 위해 ```split()```로 배열로 변경해줌 
3. 여러개의 요소를 더해 한개의 값을 도출하기 위해 ```reduce()``` 를 사용
4. 각 요소들을 숫자로 만들어 더 해주어야하기 때문에 각 요소를 숫자로 바꿔준다. ```Number()``` , ```ParseInt()```, ```+``` 중에 ```+```를 사용하여 문자열을 숫자로 형 변환
5. 마지막 조건문으로 처리
```js
function solution(x) {
let number = (x + "").split("").reduce((acc,val) => +((+acc) + (+val)));
if(x % number === 0){
return true;
}
return false;
}
```
**문제2**
https://programmers.co.kr/learn/courses/30/lessons/12901
```js
function solution(a, b) {
const date = new Date(`${a},${b},2016`);
let day= (date+"").split(' ');
return day[0].toUpperCase()
}
```
```js
function solution(a, b) {
let date = new Date(`2016, ${a} …
```
=> [ADD] Day7 solved

hyejun/JavaStudy/day10.md, hyejun/JavaStudy/day11.md, hyejun/JavaStudy/day9.md
<https://programmers.co.kr/learn/courses/30/lessons/12933?language=java>
long 형으로 받은 정수 n을 내림차순으로 정렬하여 return한다.
1. long → String 형변환하여 변수에 담아준다.
2. Stirng 변수에서 한 문자씩 읽어와 (charAt) int 배열에 넣어준다.
3. int 배열을 오름차순 sort후, 역순으로 읽어와 String변수에 대입한다.
4. String 변수를 long형으로 형변환 후, return해준다.
```java
public long solution(long n) {
long answer=0;
/*첫번째*/
String str = Long.toString(n);
String num_str="";
int[] arr=new int[str.length()];
/*두번째*/
for(int i=0; i<str.length(); i++) {
arr[i]=str.charAt(i)-'0';
}
/*세번째*/
Arrays.sort(arr);
for(int i=str.length()-1; i>=0; i--) {
num_str += arr[i];
}
/*네번째*/
answer = Long.parseLong(num_str);
return answer;
}
}
```
※ String -> Long 형변환 메소드
Integer.parseInt()를 사용했었는데, 계속 런타임 에러가 났었다.
```java
Long.parseLong(num_str);
```
로직은 나와 …
=> day9, day10

minhwan/javaStudy/day7.md
**문제1** 
https://programmers.co.kr/learn/courses/30/lessons/12947
```java
public boolean solution(int x) {
boolean answer ;
int sum =0;
int x1 =x;
while(x>0) {
sum += x%10;
x = x/10;
}
if(x1%sum == 0 ){
answer = true;
}else{
answer =false;
}
return answer;
}
}
```
* 자연수 x의 일의 자리부터 n의 자리까지 더해서 본래의 값이 더한값으로 나누어 떨어지는 값이  하샤드 수 
* while 반복문을 돌려 십의자리 수와 일의자리 수 를 더해 sum 변수에 저장
* x 가 sum 값으로 나누어 떨어지면 true반환 아니면 false 반환
**문제2**
https://programmers.co.kr/learn/courses/30/lessons/12901
```java
public String solution(int a, int b) {
String answer = "";
int[] days = {31,29,31,30,31,30,31,31,30,31,30,31};
int day = 0;
for( int i =0; i<a-1; i++) {
day += days[i];
} 
day +=b;
day = day %7;
switch(day){
case 1 :
answer += "FRI";
break;
case 2 :
answer += "SAT";
break; …
```
=> [NOT DONE]Day7 solved

hyejun/JavaStudy/Programmers (문제)/day13.md, hyejun/JavaStudy/Source Code/베스트앨범.java
<https://programmers.co.kr/learn/courses/30/parts/12077>
1. 문제
스트리밍 사이트에서 장르 별로 가장 많이 재생된 노래를 두 개씩 모아 베스트 앨범을 출시하려 합니다. 노래는 고유 번호로 구분하며, 노래를 수록하는 기준은 다음과 같습니다.
1. 속한 노래가 많이 재생된 장르를 먼저 수록합니다.
2. 장르 내에서 많이 재생된 노래를 먼저 수록합니다.
3. 장르 내에서 재생 횟수가 같은 노래 중에서는 고유 번호가 낮은 노래를 먼저 수록합니다.
노래의 장르를 나타내는 문자열 배열 genres와 노래별 재생 횟수를 나타내는 정수 배열 plays가 주어질 때, 베스트 앨범에 들어갈 노래의 고유 번호를 순서대로 return 하도록 solution 함수를 완성하세요.
2. 이해
(장르들이 저장되는 genres 배열, 플레이 횟수가 저장되는 plays 배열을) 매개변수로 받아 장르별로 플레이 횟수를 합산한다.
1. 가장 많이 재생된 장르
2. 장르에서 가장 많이 재생된 인덱스 2개를 return
​
여기서 헷갈렸던 부분이 2번 (장르에서 가장 많이 재생된 인덱스 2개를 return 하는 부분)이었다.
문제와 제한사항을 꼼꼼하게 읽어봐야겠다.
1. 이중 해시맵을 사용해  {장르 {index, play횟수}} 형태로 저장
- Key중복 저장이 안되기 때문에, inner map key를 index 값으로 저장함
2. 해시맵을 이용해 {장르 , 총 play 횟수} 형태로 저장
3. 2번에서 저장한 해시맵을 Key만 저장한 배열로 만든 후, 배열을 내림차순으로 정렬
4. 장르당 2개씩 …
=>  Day13 [Level3/hash]

hyejun/JavaStudy/Programmers (문제)/day14.md, hyejun/JavaStudy/Programmers (문제)/day15.md, hyejun/JavaStudy/Source Code/[greedy] 구명보트.java, hyejun/JavaStudy/Source Code/큰수만들기.java
<https://programmers.co.kr/learn/courses/30/lessons/42883>
어떤 숫자에서 k개의 수를 제거했을 때 얻을 수 있는 가장 큰 숫자를 구하려 한다.
​![image](https://user-images.githubusercontent.com/45223821/109332453-7997ee80-78a1-11eb-9fdd-3f4d0f217328.png)
예를 들어, 숫자 1924에서 수 두 개를 제거하면 [19, 12, 14, 92, 94, 24] 를 만들 수 있습니다. 이 중 가장 큰 숫자는 94 이다.
중요한 점은 "가장 큰 수"가 아닌 "k개의 수를 제거했을 떄 얻을 수 있는 가장 큰 수"이다.
greedy는 처음 방법을 찾는게 어려운것같다.
1. 앞 숫자와 뒷 숫자를 비교하며, 뒷 숫자가 더 크다면 앞 숫자를 삭제한다.
1-1. 1번을 k번 반복한다.
2. 1번을 실행하지 않은 경우, index 0부터 len-1까지 끊어 return한다.
ex. number = 3111, k=2 : return = 31
```java
public String solution(String number, int k) {
StringBuilder ans = new StringBuilder(number);
String answer = "";
while (k > 0) {
int len = ans.length();
boolean removed = false;
for (int i = 0; i < len - 1; i++) {
if …
```
=> [ADD] Day14 Solved

hyejun/JavaStudy/Source Code/[백준/투포인터]수들의합2.java
<https://www.acmicpc.net/problem/2003>
수들의 합2
N개의 수로 된 수열 A[1], A[2], …, A[N] 이 있다. 이 수열의 i번째 수부터 j번째 수까지의 합 A[i] + A[i+1] + … + A[j-1] + A[j]가 M이 되는 경우의 수를 구하는 프로그램을 작성하시오.
​
- 입력
첫째 줄에 N(1 ≤ N ≤ 10,000), M(1 ≤ M ≤ 300,000,000)이 주어진다. 다음 줄에는 A[1], A[2], …, A[N]이 공백으로 분리되어 주어진다. 각각의 A[x]는 30,000을 넘지 않는 자연수이다.
​
- 출력
첫째 줄에 경우의 수를 출력한다.
​
본 문제에서 모든 경우의 수를 수행한다면(BruteForce), O(N^2)의 시간 복잡도를 가지기 때문에 시간초과가 발생하게된다.
또한 이 문제는 입력의 크기가 10,000이 넘으므로 nlongn또는 n의 알고리즘을 찾아야했다.
따라서 O(N)으로 시간복잡도를 줄여야 한다.
연속된 수열에 대한 합을 찾는 문제이기 때문에 two pinters 탐색을 이용할 수 있다.
1. sum<m : end인덱스를 한칸 늘려주고, sum에 값을 추가한다.
2. sum=m : end인덱스를 한칸 늘려주고, sum에 값을 추가한 뒤, cnt++
3. sum>m : sum에서 값을 빼고, start 인덱스를 한칸 늘려준다.
```java
public class Main{
public static void main(String[] args){
Scanner sc = new …
```
=> [ADD] Day18 Solved

jangwon/leetcode/Graph/allPathsSourceTarget.md, jangwon/leetcode/Graph/findCenter.md, jangwon/leetcode/Graph/findjudge.md, jangwon/programmers/Solo/베스트앨범.md, 기업/Line/2021_상반기/problem1.md
라인 Problem1은 중첩해쉬로 다시 해결 예정입니다. 중복된 코드가 많기 때문에 향후 수정 해나가겠습니다
=> Feat: Line problem1, Graph, programmers best albujm

jangwon/Inflearn/Seciton2(이차원배열)/격자판_최대합.md, jangwon/Inflearn/Seciton2(이차원배열)/등수구하기.md, jangwon/Inflearn/Seciton2(이차원배열)/봉우리.md, jangwon/Inflearn/Section1(Basic)/가장긴문자열.md, jangwon/Inflearn/Section1(Basic)/일곱난쟁이.md, jangwon/Inflearn/Section3(문자열)/문자열압축.md, jangwon/Inflearn/Section3(문자열)/유효한팰린드롬.md
기초강의, 문자열 강의 완료 
배울 점이 있는 부분만 문제로 업로드 했습니다.
=> Feat: Inflearn Basic

jangwon/Inflearn/Section3(문자열)/가장짧은문자거리.md, jangwon/Inflearn/Section4(완전탐색)/K번째큰수.md, jangwon/Inflearn/Section4(완전탐색)/뒤집은소수.md, jangwon/Inflearn/Section4(완전탐색)/자리수의합.md, jangwon/Inflearn/Section4(완전탐색)/졸업선물.md
**Brute force**
- 뒤집은 소수
- 자리수의 합
- 졸업 선물
- k번째 큰수
**String**
- 가장짧은문자거리
- 문자열 압축
- 유효한 팰린드롬
=> Feat: Inflearn Section3 String, Section4 Brute force all problem done

jangwon/Inflearn/Section5(투포인터,효율성)/공통원소구하기.md, jangwon/Inflearn/Section5(투포인터,효율성)/두배열합치기.md, jangwon/Inflearn/Section5(투포인터,효율성)/모든애나그램찾기.md, jangwon/Inflearn/Section5(투포인터,효율성)/애나그램.md, jangwon/Inflearn/Section5(투포인터,효율성)/연속부분수열1.md, jangwon/Inflearn/Section5(투포인터,효율성)/연속부분수열2.md, jangwon/Inflearn/Section5(투포인터,효율성)/최대매출.md, jangwon/Inflearn/Section5(투포인터,효율성)/학급회장.md
* 공통 원소 구하기
* 두 배열 합치기
* 연속부분수열1
* 연속부분수열2
* 최대매출
* 학급회장
* 모든애나그램찾기
=> Feat:Inflearn Two-Pointer, hash, sliding window done

jangwon/programmers/Solo/cache.md
**프로그래머스** 
2018 kakao blind 캐시
=> Feat: Programmers sort,cache done

jangwon/Inflearn/Section7(정렬,결정트리)/LRU.md, jangwon/Inflearn/Section7(정렬,결정트리)/Special_sort.md, jangwon/Inflearn/Section7(정렬,결정트리)/결혼식.md, jangwon/Inflearn/Section7(정렬,결정트리)/버블정렬.md, jangwon/Inflearn/Section7(정렬,결정트리)/삽입정렬.md, jangwon/Inflearn/Section7(정렬,결정트리)/선택정렬.md, jangwon/Inflearn/Section7(정렬,결정트리)/이분검색.md, jangwon/Inflearn/Section7(정렬,결정트리)/장난꾸러기현수.md, jangwon/Inflearn/Section7(정렬,결정트리)/좌표정렬.md, jangwon/Inflearn/Section7(정렬,결정트리)/회의실배정.md
* 결혼식
* 버블정렬
* 삽입정렬
* 이분검색
* 장난꾸러기현수
* 좌표정렬
* 회의실배정
* LRU
* Special sort
=> Feat: Section7 sort, decision

jangwon/Inflearn/Section8(재귀함수와 완전탐색)/동전교환.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/바둑이승차.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/부분집합구하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/순열구하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/이진수출력.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/이진트리순회.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/재귀함수.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/중복순열구하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/최대점수구하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/팩토리얼.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/합이같은부분집합.md
* 동전교환
* 바둑이승차
* 부분집합구하기
* 순열구하기
* 이진수 출력
* 이진트리순회 
* 재귀함수
* 중복순열구하기
* 최대점수구하기
* 팩토리얼
* 합이같이부분집합
=> Feat: dfs, recursive

jangwon/Inflearn/Section8(재귀함수와 완전탐색)/수들의조합.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/수열추측하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/조합구하기.md, jangwon/Inflearn/Section8(재귀함수와 완전탐색)/조합수.md
* 수들의 조합
* 수열추측하기
* 조합구하기
* 조합수
=> Feat: Inflearn section8 dfs done

jangwon/leetcode/Search/BFS&DFS/getMaximumGold.md, jangwon/leetcode/Search/BFS&DFS/leafSimilar.md
* leetcode 872. Leaf-Similar Trees (Easy) solved
* Leetcode.1219 Path with Maximum Gold(Backtracking-dfs) solved
=> Feat: leetcode 872 , 1219 solved

jangwon/leetcode/Search/BFS&DFS/N-ary_tree_levelOrder.md, jangwon/leetcode/Search/BFS&DFS/canReach.md, jangwon/leetcode/Search/BFS&DFS/maxLevelSum.md
* leetcode 1306. Jump Game III
*  leetcode 429. N-ary Tree Level Order Traversal
* 1161. Maximum Level Sum of a Binary Tree
=> Feat: leetcode BFS,DFS (429,1161,1306) solved

jangwon/leetcode/Graph/networkDelayTime.md, jangwon/leetcode/String/isPalindrome.md, jangwon/leetcode/String/reverseString.md
leetcode 743. Network Delay Time (graph) solved
leetcode 125. Valid Palindrome(String) solved
leetcode 344. Reverse String(String) solved
=> Feat: leetcode 743, 125, 344 solved

jangwon/leetcode/Array/Problem/arrayPairSum.md, jangwon/leetcode/Array/Problem/productExceptSelf.md, jangwon/leetcode/linear/maxprofit.md, jangwon/leetcode/linear/twoSum.md, jangwon/leetcode/list/isPalindrome.md, jangwon/leetcode/two-pointer/3sum.md, jangwon/leetcode/two-pointer/trap.md
@jangwonyoon
Refactor: leetcode twoSum add solution
0abc2ac
@jangwonyoon
Feat: leetcode 42. Trapping Rain Water solved
5b9a0b5
@jangwonyoon
Feat: leetcode 15. 3Sum(two-pointer) solved
6ebda34
@jangwonyoon
Feat: leetcode 561. Array Partition I solved
051d4c8
Commits on Apr 26, 2021
@jangwonyoon
Feat: leetcode 238. Product of Array Except Self(Array) solved
37b4100
@jangwonyoon
Feat: leetcode 234. Palindrome Linked List solved
e03935e
@jangwonyoon
Feat: jangwon/leetcode/linear/maxprofit.md
=> Feat: leetcode 42,15,561,238,234,121 solved

jangwon/leetcode/list/24.swapPairs.md, jangwon/leetcode/list/add_Two_Numbers.md, jangwon/leetcode/list/mergeTwoLists.md, jangwon/leetcode/list/oddEvenList.md, jangwon/leetcode/list/reverseBetween.md, jangwon/leetcode/list/reverseList.md
Feat: leetcode 21. Merge Two Sorted Lists solved
ce55173
Commits on Apr 27, 2021
@jangwonyoon
Feat: leetcode 24.swapPairs solved
76d03d3
@jangwonyoon
Feat: leetcode 2. Add Two Numbers
b1ec331
@jangwonyoon
Feat: leetcode 206. Reverse Linked List solved
08c51ba
@jangwonyoon
Feat: leetcode 328. Odd Even Linked List solved
a01c18f
@jangwonyoon
Feat: leetcode 92. Reverse Linked List II solved
9cb129e
=> Feat: leetcode 21, 24, 2, 206, 328, 92

jangwon/leetcode/Search/BFS&DFS/canReach2.md, jangwon/leetcode/Search/BFS&DFS/combinationSum.md, jangwon/leetcode/Search/BFS&DFS/subsets.md, jangwon/leetcode/Search/findItinerary.md
@jangwonyoon
Feat: leetcode 39.Combination Sum solved py,js
bb36945
@jangwonyoon
Feat: leetcode 207, 46,332 solved
=> Feat: leetcode 39, 207, 46, 332 solved

jangwon/leetcode/Heap/findKthLargest.md, jangwon/leetcode/Heap/heapDegign.py, jangwon/leetcode/Heap/heapDesign.md, jangwon/leetcode/Tree/bstToGst.md, jangwon/leetcode/Tree/buildTree.md, jangwon/leetcode/Tree/findMinHeightTrees.md, jangwon/leetcode/Tree/invertTree.md, jangwon/leetcode/Tree/isBalanced.md, jangwon/leetcode/Tree/longestUnivaluePath.md, jangwon/leetcode/Tree/mergeTrees.md, jangwon/leetcode/Tree/minDiffInBST.md, jangwon/leetcode/Tree/serialize.md, jangwon/leetcode/Tree/sortedArrayToBST.md, jangwon/leetcode/Tree/travelsalDesign.md
@jangwonyoon
Feat: leetcode 687. Longest Univalue Path solved py,js
018ef78
@jangwonyoon
Feat: leetcode. 617. Merge Two Binary Trees py, js solved
a9314ad
@jangwonyoon
Feat: leetcode 226. Invert Binary Tree py, js solved
b3a6e9e
@jangwonyoon
Feat: leetcode 297. Serialize and Deserialize Binary Tree py solved
c802cc4
Commits on May 07, 2021
@jangwonyoon
Feat: leetcode 297. Serialize and Deserialize Binary Tree solved
a220964
@jangwonyoon
Feat: leetcode 310. Minimum Height Trees solved
cc5dfdf
@jangwonyoon
Feat: leetcode. 1038. Binary Search Tree to Greater Sum Tree solved
6038586
@jangwonyoon
Feat: leetcode 110. Balanced Binary Tree solved
3f7e4c2
@jangwonyoon
Feat: leetcode 108. Convert Sorted Array to Binary Search Tree solved
c85fb42
@jangwonyoon
Feat: leetcode 783. Minimum Distance …
=> Feat: leetcode Tree, Heap algorithm solved

jangwon/leetcode/Search/Binary_search/intersection.md, jangwon/leetcode/Search/Binary_search/search.md, jangwon/leetcode/Search/Binary_search/searchMatrix.md, jangwon/leetcode/Search/Binary_search/twoSum.md, jangwon/leetcode/Sort/kClosest.md
@jangwonyoon
Feat: leetcode 973. K Closest Points to Origin solved
c247639
@jangwonyoon
Feat: leetcode 704. Binary Search solved
d9743bf
@jangwonyoon
add: leetcode 704. Binary Search - bisect library use solved
05f1771
Commits on May 13, 2021
@jangwonyoon
add: leetcode intersection python solved
bba5cd3
@jangwonyoon
Feat:leetcode 167. Two Sum II - Input array is sorted pyrhon solved
137674f
@jangwonyoon
Feat: leetcode 240. Search a 2D Matrix II python solved
=> Feat: leetcode 973, 704, 167, 240
